#!/usr/bin/env bash
#Aliases/Functions to use DSCL much easier 
domain='/Active Directory/2TOR/All Domains'
#usage: get-user <user_name> 
#can pass additional arg to only grab a specific attribute
#example: get-user <user_name> FirstName
function get-user () 
{
 local user='/Users/${1}'
  eval "dscl '$domain' read $user $2"
}
