#!/usr/bin/env bash
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$HOME/dev/terravision:$PATH"
eval "$(pyenv init -)"

#api
alias be_nice="echo 'here is a tip';curl -s -X PUT https://api.gsiders.app/nice | jq .tip"
alias update_cw="ssh gsweb ./update.sh"
alias cwd="cd ~/dev/apples723/cw"
#openai
source ~/.dotfiles/private/keys
#hue commands 
source ~/.dotfiles/hue_api.sh
alias tempd="cd ~/dev/temp" 
#note
function notes {
 vi ~/notes/${1}
}

# swtich between work off on
alias woff="work_mode off; dbottom"
alias won="work_mode on; dleft"

#homelab vnc tunnels

alias ha-vnc="ssh -L 5903:localhost:5903 -C -N -l gsiders ha.gsiders.app"
alias vm-vnc="ssh -L 5901:localhost:5901 -C -N -l gsiders vm.rad"

#make file executable 
alias x="chmod 755 "
#my bash todo list 
alias todo="vi ~/todo"

#fix ssh host
alias vsf="vi ~/.ssh/known_hosts"

#Clear
alias cl="clear"
#modify this file in v1i
alias va="vi ~/.alias" 
#config files and shortcuts
alias dtf="cd ~/.dotfiles" 
alias vs="vi ~/.ssh/config"
alias app_dev="cd ~/dev/apples723 "
#Git Shortcuts 
alias gts="git status"
alias gtp="git push "
alias gtb="git branch "
alias gtco="git checkout "
alias gl="git log --pretty=oneline -n 20 --graph"
alias glp="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"


#Directory Shortcuts
alias home="cd $home"
alias up="cd .." 
alias dl="cd ~/Downloads/ "
alias dev="cd ~/dev/ "
#Terraform Shortcuts
alias tfaa="terraform apply --auto-approve"
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tf="terraform " #space at ends allows tf as shortcut for terraform but can add command at end
alias tfwp="terraform workspace select prod"
alias tfwd="terraform workspace select dev" 
alias tfw="terraform workspace "
alias tfwn="terraform workspace new "
#ansible
alias ansp="ansible-playbook "
#Dock Controls 
alias dleft="defaults write com.apple.dock orientation left; killall Dock"
alias dright="defaults write com.apple.dock orientation right; killall Dock"
alias dbottom="defaults write com.apple.dock orientation bottom; killall Dock"


