#!/usr/bin/env bash

# copy folders easier
#usage: cpd directory_to_copy new_directory_name
function cpd(){
  cp -r $1 $2 
}
# copy terraform folder for use as a template
function cpt(){
  cp -r $1 $2
  rm -rf $2/.terraform
  cp -f ~/.dotfiles/templates/main.tf $2/main.tf
}

#connect to vpn from terminal
#uses user password from keychain
#additional script at /usr/local/bin/_vpn_autoconnect is used
#see: github.com/2uinc/devops-patters/team-process/onboarding.md
vpn ()
{
    local command="${1:-status}";
    local -r _vpn_bin='/opt/cisco/anyconnect/bin/vpn';
    local -r _vpn_net='2U Corp Network';
    case "$command" in
        s | status)
            echo -e 'Checking current VPN status...\n';
            eval "${_vpn_bin} -s status"
        ;;
        c | connect)
            echo -e 'Connecting to VPN...\n';
            _vpn_autoconnect
        ;;
        d | disconnect)
            echo -e 'Disconnecting from VPN...\n';
            eval "${_vpn_bin} -s disconnect"
        ;;
        *)
            echo "Invalid option '${command}' ([s]tatus|[c]onnect|[d]isconnect)";
            return 1
        ;;
    esac
}


#modify this file in v1i
alias va="vi ~/.alias" 
# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
#Git Shortcuts 
#Need to move to .gitconfig
alias gst="git status"
alias gph="git push"
alias gbr="git branch"
# Shortcuts
alias dl="cd ~/Downloads"
alias dev="cd ~/dev"
alias awsd="cd ~/aws"
alias inf="cd ~/aws/tf-it-inf-acct"
alias ue1="cd ~/aws/tf-it-inf-acct/resources/ue1"
alias uw1="cd ~/aws/tf-it-inf-acct/resources/uw1"
alias sandbox="cd ~/aws/tf-inf-sandbox/"
#aws commands 
#show ec2 info 
#usage: ec2 <tag:name> 
function ec2(){
  aws ec2 describe-instances --filters "Name=tag:Name,Values=$@" --profile sub --region=us-east-1 --output table
}
#terraform commands 
alias tfaa="terraform apply --auto-approve"
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
#AWS creds generator
alias 2l="2u-login"


#connects Windows Admin Center to https://wac
#need to map in hosts localhost:443 -> wac
alias wac-tunnel="~/mole tunnel 9443:UE1MGMT01:443 --profile sub --region us-east-1"
#add rdp tunnel 
#usage:
#   rdp-tunnel <hostname> <region>
#          Hostname: value of tag:Name
#          Region: region of host (i.e us-east-1 )
function rdp-tunnel(){
  ~/mole tunnel 3389:$1:3389 --profile sub --region $2
}
# Detect which `ls` flavor is in use
if ls i--color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # macOS `ls`
	colorflag="-G"
	export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi
#list all hidden files in directory
alias l.="ls -all -lF| grep ."
# List all files colorized in long format
alias l="ls -lF ${colorflag}"

# List all files colorized in long format, excluding . and ..
alias la="ls -lAF ${colorflag}"

# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls ${colorflag}"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '
# Google Chrome
alias chrome='/Applicationsd/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"


# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"
#probably should find a spotify cli app....
alias sp=/Applications/Spotify.app/Contents/MacOS/spotify

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"
#doessn't not seem to work in BigSur
# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"
alias path='echo -e ${PATH//:/\\n}'
