#!/usr/bin/env bash

#hue commands 
source ~/.dotfiles/hue_api.sh

#note
function notes {
 vi ~/notes/${1}
}

#homelab vnc tunnels

alias ha-vnc="ssh -L 5903:localhost:5903 -C -N -l gsiders ha.gsiders.app"
alias vm-vnc="ssh -L 5901:localhost:5901 -C -N -l gsiders vm.rad"

# copy folders easier
#usage: cpd directory_to_copy new_directory_name
function cpd(){
  cp -r $1 $2 
}
# copy terraform folder for use as a template
function cpt(){
  cp -r $1 $2
  rm -rf $2/.terraform
  cp -f ~/.dotfiles/templates/main.tf $2/main.tf
}

#make file executable 
alias x="chmod 755 "
#my bash todo list 
alias todo="vi ~/todo"
alias wip="cd  ~/dev/repos/2u/wip"
#connect to vpn from terminal
#uses user password from keychain
#additional script at /usr/local/bin/_vpn_autoconnect is used
#see: github.com/2uinc/devops-patters/team-process/onboarding.md
vpn ()
{
    local command="${1:-status}";
    local -r _vpn_bin='/opt/cisco/anyconnect/bin/vpn';
    local -r _vpn_net='2U Corp Network';
    case "$command" in
        s | status)
            echo -e 'Checking current VPN status...\n';
            eval "${_vpn_bin} -s state"
        ;;
        c | connect)
            echo -e 'Connecting to VPN...\n';
            _vpn_autoconnect
        ;;
        d | disconnect)
            echo -e 'Disconnecting from VPN...\n';
            eval "${_vpn_bin} -s disconnect"
        ;;
        *)
            echo "Invalid option '${command}' ([s]tatus|[c]onnect|[d]isconnect)";
            return 1
        ;;
    esac
}
#Clear
alias cl="clear"
#AWS creds generator
alias 2l="__auto_2u_login"
#modify this file in v1i
alias va="vi ~/.alias" 
#config files and shortcuts
alias dot="cd ~/.dotfiles" 
alias vs="vi ~/.ssh/config"
#Git Shortcuts 
alias gts="git status"
alias gtp="git push "
alias gtb="git branch "
alias gtco="git checkout "
alias gl="git log --pretty=oneline -n 20 --graph"
alias glp="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"


#Directory Shortcuts
alias 2ur="cd ~/dev/repos/2u"
alias home="cd $home"
alias up="cd .." 
alias dl="cd ~/Downloads/ "
alias dev="cd ~/dev/ "
alias awsd="cd ~/aws/ "
alias inf="cd ~/aws/tf-it-inf-acct "
alias inf_ue1="cd ~/aws/tf-it-inf-acct/resources/ue1 "
alias inf_uw1="cd ~/aws/tf-it-inf-acct/resources/uw1 "
alias inf_sandbox="cd ~/aws/tf-inf-sandbox/ "
alias inf_gr="cd ~/aws/tf-it-inf-acct/global-resources"
alias tfd="cd ~/dev/repos/2u/tf"
alias tfops="cd ~/dev/repos/2u/tf/tf-devops"

#Terraform Shortcuts
alias tfaa="terraform apply --auto-approve"
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tf="terraform " #space at ends allows tf as shortcut for terraform but can add command at end
alias tfwp="terraform workspace select prod"
alias tfwd="terraform workspace select dev" 
alias tfw="terraform workspace "
alias tfwn="terraform workspace new "
#ansible
alias ansp="ansible-playbook "

#IMPORTS 
#Active Directory
source ~/.dotfiles/ad_mgmt_alias
#AWS
source ~/.dotfiles/aws_aliases
#Kube
source ~/.dotfiles/k8s_aliases
#stolen aliases
source ~/.dotfiles/stolen_aliases
